/**
 * GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Run `npm run images` after changing anything in image-sources/.
 *
 * Keyed by the original source path so call sites keep referring to
 * "/Images/Marigot 1.jpg" and <ResponsiveImage> resolves the variants.
 */
export interface OptimizedImage {
  /** Path prefix shared by every variant: `${base}-${width}${format}`. */
  base: string;
  /** Available AVIF widths, ascending. Never wider than the source. */
  widths: number[];
  /** Extension of the universal fallback ladder — '.jpg' or '.png'. */
  ext: string;
  /** Available fallback widths, ascending. A coarser subset of `widths`. */
  fallbackWidths: number[];
  /** Width used for the plain `src` attribute. Always in `fallbackWidths`. */
  fallbackWidth: number;
  /** Intrinsic source dimensions, used to reserve layout space. */
  width: number;
  height: number;
}

export const OPTIMIZED_IMAGES: Record<string, OptimizedImage> = {
  "/Images/Island Zone.jpg": {
    base: "/Images/optimized/island-zone",
    widths: [320, 480, 768, 1024, 1440],
    ext: ".jpg",
    fallbackWidths: [320, 768, 1024, 1440],
    fallbackWidth: 1024,
    width: 1920,
    height: 2172,
  },
  "/Images/Jojo 1.jpg": {
    base: "/Images/optimized/jojo-1",
    widths: [320, 480, 768, 1024, 1440],
    ext: ".jpg",
    fallbackWidths: [320, 768, 1024, 1440],
    fallbackWidth: 1024,
    width: 1920,
    height: 2560,
  },
  "/Images/Jojo 2.jpg": {
    base: "/Images/optimized/jojo-2",
    widths: [320, 480, 768, 1024],
    ext: ".jpg",
    fallbackWidths: [320, 768, 1024],
    fallbackWidth: 1024,
    width: 1280,
    height: 1707,
  },
  "/Images/Jojo 3.jpg": {
    base: "/Images/optimized/jojo-3",
    widths: [320, 480, 768],
    ext: ".jpg",
    fallbackWidths: [320, 768],
    fallbackWidth: 768,
    width: 800,
    height: 1067,
  },
  "/Images/Lexus_1.jpg": {
    base: "/Images/optimized/lexus-1",
    widths: [320, 480, 768, 1024, 1440],
    ext: ".jpg",
    fallbackWidths: [320, 768, 1024, 1440],
    fallbackWidth: 1024,
    width: 6787,
    height: 4525,
  },
  "/Images/Logo.png": {
    base: "/Images/optimized/logo",
    widths: [96, 144, 192, 288],
    ext: ".png",
    fallbackWidths: [96, 192],
    fallbackWidth: 192,
    width: 1024,
    height: 1024,
  },
  "/Images/Marigot 1.jpg": {
    base: "/Images/optimized/marigot-1",
    widths: [320, 480, 768, 1024],
    ext: ".jpg",
    fallbackWidths: [320, 768, 1024],
    fallbackWidth: 1024,
    width: 1280,
    height: 719,
  },
  "/Images/Pitons 1.jpg": {
    base: "/Images/optimized/pitons-1",
    widths: [320, 480, 768, 1024, 1440, 1920],
    ext: ".jpg",
    fallbackWidths: [320, 768, 1024, 1440],
    fallbackWidth: 1024,
    width: 3075,
    height: 1920,
  },
  "/Images/SLU Airport.jpg": {
    base: "/Images/optimized/slu-airport",
    widths: [320, 480, 768, 1024, 1440],
    ext: ".jpg",
    fallbackWidths: [320, 768, 1024, 1440],
    fallbackWidth: 1024,
    width: 1708,
    height: 1280,
  },
  "/Images/Toyota_1.jpg": {
    base: "/Images/optimized/toyota-1",
    widths: [320, 480, 768, 1024, 1440],
    ext: ".jpg",
    fallbackWidths: [320, 768, 1024, 1440],
    fallbackWidth: 1024,
    width: 4537,
    height: 3015,
  },
  "/Images/UVF Airport.jpg": {
    base: "/Images/optimized/uvf-airport",
    widths: [320, 480, 768, 1024, 1440],
    ext: ".jpg",
    fallbackWidths: [320, 768, 1024, 1440],
    fallbackWidth: 1024,
    width: 3413,
    height: 1920,
  },
  "/Images/Viewpoint 1.jpg": {
    base: "/Images/optimized/viewpoint-1",
    widths: [320, 480, 768],
    ext: ".jpg",
    fallbackWidths: [320, 768],
    fallbackWidth: 768,
    width: 800,
    height: 446,
  },
  "/Images/Viewpoint 2.jpg": {
    base: "/Images/optimized/viewpoint-2",
    widths: [320, 480, 768, 1024, 1440],
    ext: ".jpg",
    fallbackWidths: [320, 768, 1024, 1440],
    fallbackWidth: 1024,
    width: 3413,
    height: 1920,
  },
  "/Images/Viewpoint 3.jpg": {
    base: "/Images/optimized/viewpoint-3",
    widths: [320, 480, 768],
    ext: ".jpg",
    fallbackWidths: [320, 768],
    fallbackWidth: 768,
    width: 800,
    height: 600,
  },
  "/Images/Waterfall 1.jpg": {
    base: "/Images/optimized/waterfall-1",
    widths: [320, 480],
    ext: ".jpg",
    fallbackWidths: [320, 480],
    fallbackWidth: 480,
    width: 600,
    height: 401,
  },
  "/Images/Waterfall 2.jpg": {
    base: "/Images/optimized/waterfall-2",
    widths: [320, 480, 768],
    ext: ".jpg",
    fallbackWidths: [320, 768],
    fallbackWidth: 768,
    width: 800,
    height: 1067,
  },
  "/Images/Waterfall 3.jpg": {
    base: "/Images/optimized/waterfall-3",
    widths: [320, 480, 768],
    ext: ".jpg",
    fallbackWidths: [320, 768],
    fallbackWidth: 768,
    width: 800,
    height: 600,
  },
  "/Images/Waterfall 4.jpg": {
    base: "/Images/optimized/waterfall-4",
    widths: [320, 480, 768],
    ext: ".jpg",
    fallbackWidths: [320, 768],
    fallbackWidth: 768,
    width: 800,
    height: 1067,
  },
};
